# Generated by Django 5.0.2 on 2024-03-06 17:58

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='course_name', unique=True)),
                ('course_price', models.CharField(default=None, max_length=10)),
                ('course_offer_price', models.CharField(default=None, max_length=10)),
                ('course_description', models.TextField()),
                ('course_type', models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], max_length=10)),
                ('course_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('thumbnail', models.ImageField(blank=True, default='course/default.png', null=True, upload_to=models.CharField(max_length=250, unique=True))),
                ('create_at', models.DateField(auto_now=True, null=True)),
                ('update_at', models.DateField(auto_now=True, null=True)),
                ('delete_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TF', 'True/False Question'), ('SA', 'Short Answer Question')], max_length=3)),
                ('points', models.CharField(default=None, max_length=50)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quizzes')),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('is_correct', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quizquestions')),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(default=None, max_length=50)),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('randomize_questions', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('attempts_allowed', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quizzes'),
        ),
        migrations.CreateModel(
            name='QuizAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('score', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed')], max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quizzes')),
            ],
        ),
    ]
