# Generated by Django 5.0.2 on 2024-03-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_quizquestions_quizchoices_quizzes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='choices',
            field=models.ManyToManyField(related_name='questions', to='home.quizchoices'),
        ),
    ]
