# Generated by Django 5.0.2 on 2024-03-17 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_quizquestions_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='choices',
        ),
        migrations.AlterField(
            model_name='quizchoices',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='home.quizquestions'),
        ),
    ]
