# Generated by Django 5.0.2 on 2024-03-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_quizquestions_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizchoices',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='quizquestions',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
