# Generated by Django 5.0.2 on 2024-03-17 17:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_quiz_quizquestions_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='quiz_name', unique=True),
        ),
    ]
